services:
  web:
    build: .
    container_name: bookio_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    stdin_open: true
    tty: true
