# Generated by Django 6.0.5 on 2026-05-20 17:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUERO_LER', 'Quero Ler'), ('LENDO', 'Lendo'), ('LIDO', 'Lido'), ('ABANDONADO', 'Abandonado')], default='QUERO_LER', max_length=20)),
                ('paginas_lidas', models.PositiveIntegerField(default=0)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('nota', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras_usuarios', to='catalogo.livro')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leitura',
                'verbose_name_plural': 'Leituras',
                'unique_together': {('pessoa', 'livro')},
            },
        ),
        migrations.CreateModel(
            name='SessaoLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_leitura', models.DateField(auto_now_add=True)),
                ('paginas_avancadas', models.PositiveIntegerField()),
                ('leitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='leitura.leitura')),
            ],
            options={
                'verbose_name': 'Sessão de Leitura',
                'verbose_name_plural': 'Sessões de Leitura',
            },
        ),
    ]
